### ISSUE TITLE
terminus-font: remove dep on bdftopcf

### ISSUE THREAD

**Issue by aabacchus** [kiss-community/community#1000]
https://tmp.bvnf.space/0001-terminus-font-remove-dep-on-bdftopcf.patch

bdftopcf was dropped in 60049314

**Comment by git-bruh** [comment]
@aaronNGi

**Comment by aabacchus** [comment]
NB: bdftopcf produced the X11 fonts, so with this patch, only terminal fonts are generated.

**Comment by slave66** [comment]
I use this font in sway, will it be supported?

**Comment by dilyn-corner** [comment]
Because @aaronNGi has been AWOL for a while, I've taken the liberty of merging this patch as it technically should have been included with our dropping of X packages.
