### ISSUE TITLE
rsync: Explictly specify DESTDIR

### ISSUE THREAD

**Issue by TAAPArthur** [kiss-community/community#1001]
@ioraff
Requesting that DESTDIR be explicitly stated when building
```
make DESTDIR="$1" install
```

I believe this is the standard for this repo and also makes it more compitable with other kiss-like package managers

**Comment by dilyn-corner** [comment]
Echoing what I said in https://github.com/kiss-community/repo/pull/49 -- there is no particular style requirement and this is 100% up to the discretion of any given maintainer. I do not care either way, and so long as `kiss` supports an implicit `DESTDIR` we will allow packages which use it.
