### ISSUE TITLE
nss missing some headers

### ISSUE THREAD

**Issue by dilyn-corner** [kiss-community/community#1109]
https://github.com/kiss-community/community/blob/7429b791a7f7340eb37c755c4dac3b2fbf407b0d/community/nss/build#L17-L23

Building `chromium` & `qt5-webengine` requires the `obsolete` headers, and they were lost in the transition.

Add:
`install -Dt "$1/usr/include/nss/obsolete" \
    -m644 dist/Linux*/include/obsolete/*.h`

@ioraff

**Comment by ioraff** [comment]
Not able to reproduce. I can build `qt5-webengine` and `chromium` 100, 101, and 102 without them. There's also no such matching directory `dist/Linux*/include/obsolete` when I build `nss`.
