### ISSUE TITLE
libmupdf build fails with lld or mold

### ISSUE THREAD

**Issue by aabacchus** [kiss-community/community#1160]
@ioraff
```
make: *** [Makefile:190: build/shared-release/resources/fonts/urw/NimbusMonoPS-Bold.cff.o] Error 1
```
The problematic commands are like:

    $ ld -r -b binary -z noexecstack -o build/shared-release/resources/fonts/urw/Dingbats.cff.o resources/fonts/urw/Dingbats.cff
works with GNU ld.

with mold:

    mold: fatal: mold does not suppor `-b binary`. If you want to convert a binary file into an object file, use `objcopy -I binary -O default <input-file> <output-file.o>` instead.

with lld:

    ld.lld: error: target emulation unknown: -m or at least one .o file required

Fix: change the definition of OBJCOPY_CMD on line 66 of the Makefile to use `objcopy -I binary -O default $< $@`.

**Comment by ioraff** [comment]
Thanks
