### ISSUE TITLE
No qt5 linguist tools

### ISSUE THREAD

**Issue by LoganDark** [kiss-community/community#1163]
The qt5 package doesn't include the linguist tools, so KeePassXC will not build.

I cannot find any information online on how to build or even obtain the source code for the linguist tools. The Gentoo ebuild is not helpful to me, as it inherits some monolithic qt5 build library and does obscure build system magic that I don't understand.

I can't find any existing linguist packages and also can't find any "qt5-tools" or similar.

Also writing *this* issue on mobile, because without KeePassXC I can't sign into GitHub on my new KISS system. :/

**Comment by ioraff** [comment]
Indeed, `qt5-tools` has not been packaged, and you'll need to do it yourself. Alpine is typically a good starting point: https://git.alpinelinux.org/aports/tree/community/qt5-qttools/APKBUILD.

**Comment by LoganDark** [comment]
Thanks!

**Comment by dilyn-corner** [comment]
You can also check my build of it [here](https://github.com/dilyn-corner/KISS-kde/tree/master/extra/qt5-tools) :)
