### ISSUE TITLE
pull request template is outdated

### ISSUE THREAD

**Issue by wael444** [kiss-community/community#1177]
https://github.com/kiss-community/community/blob/10858250374419a5fec0d2f2e841d2f7bb6f5f14/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L3

https://k1sslinux.org is no longer in use, new domain is https://kisslinux.org
also the community style is removed from the wiki, consider linking to the README directly

**Comment by ioraff** [comment]
Thanks!
