### ISSUE TITLE
Chromium 104

### ISSUE THREAD

**Issue by nvidiaLinuxUser** [kiss-community/community#1191]
Is it possible to build the latest version of chromium in KISS Linux? The latest version in this repository is 100. I prefer it over firefox.

**Comment by wael444** [comment]
why do you prefer it over firefox? just asking lol.

**Comment by nvidiaLinuxUser** [comment]
I can't say for sure, it's more a matter of habit. In general, testing has shown that chromium is faster than firefox, but I use it because of better scrolling. I also like the design compared to Firefox. And it doesn't depend on Rust. The reasons are really many.

**Comment by ehawkvu** [comment]
@nvidiaLinuxUser I have a version in kiss-xorg under testing, and the current package in community builds. Porting it over to wayland should be pretty straightforward

**Comment by ioraff** [comment]
I've got this: https://github.com/ioraff/kiss-personal/tree/master/extra/chromium. It compiles fine with gcc. It seems to work fine, too, with the exception that it segfaults when visiting youtube.com (I assume this also happens on other sites that I haven't found yet).

**Comment by nvidiaLinuxUser** [comment]
> I've got this: https://github.com/ioraff/kiss-personal/tree/master/extra/chromium. It compiles fine with gcc. It seems to work fine, too, with the exception that it segfaults when visiting youtube.com (I assume this also happens on other sites that I haven't found yet).

Thanks, I'll try

**Comment by wael444** [comment]
#1202 , chromium will get dropped, please consider adopting it.

**Comment by ioraff** [comment]
The segfaults seem to be fixed when compiling with clang.

**Comment by ehawkvu** [comment]
@ioraff 
I'm getting an error about missing wayland header files using kiss-xorg's testing package: https://0x0.st/o9Pq.ndkLfF

My immediate guess is the optional-atk-dbus patch.

**Comment by ioraff** [comment]
try this https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/chromium/files/chromium-104-swiftshader-no-wayland.patch

**Comment by ehawkvu** [comment]
I'll test that out tomorrow, thanks for the link!

**Comment by ehawkvu** [comment]
Patch applied, I'm running a build now.

**Comment by ioraff** [comment]
The gcc crash is fixed with https://github.com/ioraff/kiss-personal/blob/master/extra/chromium/patches/EnumTable-crash.patch

**Comment by nvidiaLinuxUser** [comment]
Yesterday I spent 5 hours compiling this monster, but in the end it failed because I forgot to enable swap :C
Maybe someday...

**Comment by nvidiaLinuxUser** [comment]
@git-bruh Thank you!
