### ISSUE TITLE
New package: fzy

### ISSUE THREAD

**Issue by Vouivre** [kiss-community/community#1211]
Hello,

I use the fuzzy finder `fzy`which is more lightweight than `fzf`and written in C. The code
is also much shorter than `fzf`. 

The official version is at

https://github.com/jhawthorn/fzy

It's not very active at the moment. I need the feature with multi-selection, which is not implemented in 
the official repository. But there is a PR which add this feature as well as other features:

https://github.com/jhawthorn/fzy/pull/170

The repository of the user who submitted the patch:

https://github.com/leo-arch/fzy

I could package `fzy` as I use it. Of if somebody else want to create it, no problem. 

As I'm only interested by the version with multi-selection, what do you think about packaging the version of
leo-arch which is not the official one ? Or the official version with a patch with all added features of leo-arch ?

**Comment by dilyn-corner** [comment]
Probably prefer upstream with a patch file. 

Aug 24, 2022, 11:07 AM by ***@***.***:

**Comment by Vouivre** [comment]
Ok, it's ready, I'll wait the opinion of another user before creating a PR.

**Comment by hovercats** [comment]
@dylin-corner `fzy` is partially compatible with `ytfzf`, and probably more compatible with the afforementioned features patched in.

would we be interested in patching `ytfzf` to be used with `fzy` instead?
I personally already do this, just without the afforementioned features, as I dont personally need them.

or perhaps even replacing `fzf` altogether.

**Comment by Vouivre** [comment]
@hovercats: I like the idea to replace `fzf` with `fzy`. A feature `fzf`has and not `fzy` is the preview function. 
I don't really use it at the moment, but I have it in mind. It could be useful. So I wouldn't drop `fzf` for `fzy`.

I have done another test with another patch, for me the above patch is enough. I let you create the PR. 

For patching `ytfzf` as you mentionned we should wait the opinion of users of `ytfzf` and @dilyn-corner . 
For me there would be no problem to replace. But instead I could ask the dev of `ytfzf` if it could be possible for the user to choose between `fzf`and `fzy`in the config file.

**Comment by hovercats** [comment]
> @hovercats: I like the idea to replace `fzf` with `fzy`. A feature `fzf`has and not `fzy` is the preview function. I don't really use it at the moment, but I have it in mind. It could be useful. So I wouldn't drop `fzf` for `fzy`.
> 
if you really want/need `fzf`'s extra features, stick with `fzf`. if youre happy with could ofcourse package `fzy` with the appropriate patch, to add the afforementioned features.

> I have done another test with another patch, for me the above patch is enough. I let you create the PR.

link the patch you wish to use, and ill create a pr for it once im back on my laptop.

> For patching `ytfzf` as you mentionned we should wait the opinion of users of `ytfzf` and @dilyn-corner . For me there would be no problem to replace. But instead I could ask the dev of `ytfzf` if it could be possible for the user to choose between `fzf`and `fzy`in the config file.

I doubt the maintainer of `ytfzf` is interested in doing this, as itll likely complicate the script further.
if we wish to switch out `fzf` for `fzy` and patch `ytfzf`, a new issue should probably be created, as its 2 separate things.

**Comment by Vouivre** [comment]
> if you really want/need `fzf`'s extra features, stick with `fzf`. if youre happy with could ofcourse package `fzy` with the appropriate patch, to add the afforementioned features.

No, I keep only one extra feature in mind. For the moment I'll switch completely to `fzy`.

> > I have done another test with another patch, for me the above patch is enough. I let you create the PR.
> 
> link the patch you wish to use, and ill create a pr for it once im back on my laptop.

https://github.com/jhawthorn/fzy/pull/170

> > For patching `ytfzf` as you mentionned we should wait the opinion of users of `ytfzf` and @dilyn-corner . For me there would be no problem to replace. But instead I could ask the dev of `ytfzf` if it could be possible for the user to choose between `fzf`and `fzy`in the config file.
> 
> I doubt the maintainer of `ytfzf` is interested in doing this, as itll likely complicate the script further. if we wish to switch out `fzf` for `fzy` and patch `ytfzf`, a new issue should probably be created, as its 2 separate things.

I had a look at `ytfzf`and I'm convinced the maintainer won't make this change. To use `ytfzf`with `fzy`
you need to add in `conf.sh`

    external_menu(){
                      fzy 
    }

and then call `ytfzf` with:
 
    $ ytfzf -D

So I think we could forget about the second issue.
