### ISSUE TITLE
cups-filters: new dependency libexif

### ISSUE THREAD

**Issue by Vouivre** [kiss-community/community#1252]
With the last version of `cups-filters`a new depedency is needed: `libexif`. I have created a package:

```
4KB	/var/db/kiss/installed/libexif/version
4KB	/var/db/kiss/installed/libexif/sources
4KB	/var/db/kiss/installed/libexif/manifest
1MB	/var/db/kiss/installed/libexif/libexif-0.6.24.tar.bz2
4KB	/var/db/kiss/installed/libexif/depends
4KB	/var/db/kiss/installed/libexif/checksums
4KB	/var/db/kiss/installed/libexif/build
4KB	/usr/share/doc/libexif/SECURITY.md
8KB	/usr/share/doc/libexif/README
12KB	/usr/share/doc/libexif/NEWS
68KB	/usr/share/doc/libexif/ChangeLog
28KB	/usr/share/doc/libexif/COPYING
4KB	/usr/share/doc/libexif/AUTHORS
92KB	/usr/share/doc/libexif/ABOUT-NLS
4KB	/usr/lib/pkgconfig/libexif.pc
308KB	/usr/lib/libexif.so.12.3.4
0KB	/usr/lib/libexif.so.12
0KB	/usr/lib/libexif.so
440KB	/usr/lib/libexif.a
8KB	/usr/include/libexif/exif-utils.h
12KB	/usr/include/libexif/exif-tag.h
8KB	/usr/include/libexif/exif-mnote-data.h
4KB	/usr/include/libexif/exif-mem.h
4KB	/usr/include/libexif/exif-log.h
8KB	/usr/include/libexif/exif-loader.h
4KB	/usr/include/libexif/exif-ifd.h
4KB	/usr/include/libexif/exif-format.h
8KB	/usr/include/libexif/exif-entry.h
12KB	/usr/include/libexif/exif-data.h
4KB	/usr/include/libexif/exif-data-type.h
8KB	/usr/include/libexif/exif-content.h
4KB	/usr/include/libexif/exif-byte-order.h
4KB	/usr/include/libexif/_stdint.h
2MB total
```

The given size is a little bit above 1 MB. It was introduced because some pictures were scaled to fit in a page. With `libexif`it's possible to print a picture without scaling it, so it can keep it's original size. [Here is the issue](https://github.com/OpenPrinting/cups-filters/issues/362).

I don't have packaged `libexif` properly, but I expect a few dependencies, probably none. Without packaging it, it's probably not possible to avoid a scaling for a picture. 

It's possible to remove the dependency with `--disable-exif`.

Until now, I never had such a problem, I rarely print pictures smaller than A4. 

I would tend to add the `libexif` dependency, but I would like to know the opinion of other users and @dilyn-corner .

**Comment by git-bruh** [comment]
Should be OK, libexif doesn't seem to require anything other than libc either

**Comment by Vouivre** [comment]
@git-bruh @dilyn-corner 

I've checked, no dependencies are needed. So as you wrote, libc must be enough. Do you confirm `libexif`can be added. ?

**Comment by git-bruh** [comment]
Yes

Also, you don't have to ask for approval for such decisions cuz they're within the KISS "guidelines" (no dbus etc)
