### ISSUE TITLE
elinks fails to link if libexecinfo is installed

### ISSUE THREAD

**Issue by aabacchus** [kiss-community/community#1269]
@TAAPArthur: https://github.com/rkd77/elinks/issues/191

A fix on our end could be to manually set `HAVE_EXECINFO=no`, or

```sh
if kiss l libexecinfo >/dev/null 2>&1; then
    sed '/^LIBS /s/$/ -lexecinfo/' Makefile.config >_
    mv _ Makefile.config
fi
```

**Comment by TAAPArthur** [comment]
Personally dislike the check if a packaged is installed hack. 

I think I'm fine with just setting `HAVE_EXECINFO=no` in the build file if that solves the problem. Feel free to open a PR that does that.
