### ISSUE TITLE
Packages needing attention

### ISSUE THREAD

**Issue by aabacchus** [kiss-community/community#1285]
@FriendlyNeighborhoodShane
- ~~ntfs-3g~~

@tslilc
- crispy-doom
- jfsutils
- sdl2_image
- sdl2_mixer
- sdl2_net
- unbound
- zig

Please see the issue https://codeberg.org/kiss-community/community/issues/1506. I'm afraid I only have your Github usernames as contacts, hence the issue here. If you'd like to drop your packages, that's ok! Just let us know.

**Comment by FriendlyNeighborhoodShane** [comment]
Hi @aabacchus,

Sorry but I don't have a codeberg account, and more importantly, haven't been using KISS recently.
So yes, someone else should probably pick ntfs-3g up if they wish to (along with my other packages, which IIRC included a bunch of sway-related programs, nano, nnn, etc.).

**Comment by aabacchus** [comment]
Thank you for letting us know.

**Comment by tslilc** [comment]
Hi @aabacchus , thanks for reaching out. Unfortunately i too do not use kiss any longer (or at least, not regularly). Let's drop these for now and if something changes in the future i'll make a PR again.
