### ISSUE TITLE
Package JVM

### ISSUE THREAD

**Issue by jedahan** [kiss-community/community#28]
The JVM is important, we should package it.

See trbednarzyk/KISS-Java-Repo and what it can do.

**Comment by mmatongo** [comment]
Already on this, their repo was not properly packaged but I intend on using that as a bootstrap repo.

**Comment by SpicyForthProgrammer** [comment]
Any update on the status of JVM?

**Comment by dilyn-corner** [comment]
Closed for lack of progress.
