### ISSUE TITLE
libtermkey: fix patch

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/community#339]
Hi @dantehaversham, the libtermkey build can fail on certain systems if the `ncurses` pkg-config file specifies some LDFLAGS (`pkg-config --libs ncursesw: -Wl,-O1 -Wl,--as-needed -O3 ...`), so an extra `-Wl` is added which causes the linker to error out. The solution is to modify the patch like [this](http://0x0.st/-abM.diff). The `-rpath` flag is not really needed here anyways. The patches can also be changed into a single small patch like [here](http://0x0.st/-abT.diff), the `post-install` file can be removed too.

Thanks.

**Comment by dantehaversham** [comment]
This looks great, I'll go ahead ans open a pull request with these changes when I get home.

**Comment by dilyn-corner** [comment]
Ping @dantehaversham
