### ISSUE TITLE
aerc: add GOPATH and GO111MODULE

### ISSUE THREAD

**Issue by sdsddsd1** [kiss-community/community#423]
@38061852+muevoid@users.noreply.github.com

Adding the following to the build script prevents cluttering $HOME with GO stuff. Are you still around? I havent seen you in a while. 

Greetings. 
```
export GOPATH="$PWD/go"
export GO111MODULE=on 
```

**Comment by sdsddsd1** [comment]
After 2 weeks of my initial comment I would sent a PR wit my proposed changes. Is this ok, since the user seems to be inactive?

**Comment by git-bruh** [comment]
I think it didn't ping them since you typed out an email address instead of the username.﻿

**Comment by sdsddsd1** [comment]
@muevoid does not work.

**Comment by dilyn-corner** [comment]
I've also only seen Muevoid once in the last year, so I think it's somewhat safe to assume they're /busy/.
Feel free to submit a PR :)

**Comment by sdsddsd1** [comment]
Done.
