### ISSUE TITLE
i3 version file is broken

### ISSUE THREAD

**Issue by dilyn-corner** [kiss-community/community#455]
@ominitay

Something terrible happened when we merged your last commit :)

**Comment by Ominitay** [comment]
ohhhh i see :/ let me fix that really quick
i'm disappointed i didn't notice it

**Comment by dilyn-corner** [comment]
Don't sweat it. That it wasn't discovered until now is interesting to note!

**Comment by Ominitay** [comment]
For sure! I guess we'll need to keep an eye out for erroneous line-breaks in future.
