### ISSUE TITLE
Missing GPG signature on the last commit 73b1f1e

### ISSUE THREAD

**Issue by diamant711** [kiss-community/community#475]
Hi! I am really enjoying KISS Linux! 
Today I tried to update the system using the `kiss update` command, and I recived this error:
`fatal: Commit 73b1f1e does not have a GPG signature.`
I think it's a problem with this commit but I don't rule out that i may have done something wrong with my KISS build. 
Let me know! :D

**Comment by dilyn-corner** [comment]
Checkout some of the older messages [here](https://freenode.logbot.info/?q=signed&ch=kisslinux&w=a) - this is a known issue, but it's not related to `kiss`. It's a `git` thing.
