### ISSUE TITLE
o/

### ISSUE THREAD

**Issue by dylanaraps** [kiss-community/community#494]
Hello,

I'd like to first off apologize for my abrupt disappearance from the face of the
earth and the subsequent disruption to the maintenance of KISS. As you are 
likely aware, I went through a period of burnout and dropped *everything*.

I've just come back online this month and am slowing reintegrating myself
into my work (among other things). I can't say for certain as to when I'll be
back in full capacity; I'm taking things a step at a time.

Just wanted to say thank you to the community and especially @dilyn-corner 
for taking up the reins in my absence. You have done me a service I can't 
hope to ever repay. 

All the best,

Dylan

PS I'll hop onto the IRC soon so we can all catch up. :)

**Comment by sdsddsd1** [comment]
o/

**Comment by dilyn-corner** [comment]
o7

**Comment by jedahan** [comment]
\o/

**Comment by aaronNGi** [comment]
Yo Dylan.

Glad to hear you are doing well. I don't think anyone was actually upset when you disappeared. So no bad blood at all and I'm sure everybody would be glad to have you back in irc or even in charge, if you feel like it.

**Comment by illiliti** [comment]
I'm so glad you're back!

**Comment by jedavies-dev** [comment]
Great news!

**Comment by mcpcpc** [comment]
Some of the best news I have heard in a while.  Welcome back! o/

**Comment by kyx0r** [comment]
o/ glad to witness this historical moment and welcome back. The fate of Kiss has fallen in the hands of right people while you were back, so it still rocks to be the best distr!

**Comment by AndreiSva** [comment]
Welcome back!

**Comment by konimex** [comment]
>PS I'll hop onto the IRC soon so we can all catch up.

Just a heads-up: 
Since freenode's takeover, most of us have moved to irc.libera.chat, run by the old freenode staff pre-takeover.

Also, welcome back!

**Comment by budRich** [comment]
Nice!

If anything, kiss not going under with your absence, prove that your model of a project that a single person should be able to manage works. Ironically your burn out also prove that it doesn't work ;) 

Welcome back!

**Comment by git-bruh** [comment]
👋﻿

**Comment by Xeno-Hypster** [comment]
Welcome back welcome back!

**Comment by xuxiaodong** [comment]
Welcome back!

**Comment by Vouivre** [comment]
It's a great moment and I'm really happy to read your words! 

Welcome back!

**Comment by subnut** [comment]
Phew! Relieved to see you back.

> As you are likely aware, I went through a period of burnout and dropped everything.

No. No, I wasn't aware. I was thinking that you were [hit by a bus](https://en.wikipedia.org/wiki/Bus_factor)

**Comment by tagirov** [comment]
dude!!! glad to see that you're fine

**Comment by tagirov** [comment]
dude!!! glad to hear you're fine

**Comment by tagirov** [comment]
dude!!! glad to hear you're well

**Comment by tagirov** [comment]
dude!!! I'm glad to hear you're well

**Comment by GullikX** [comment]
o7

**Comment by dilyn-corner** [comment]
Sufficiently welcomed :)
