### ISSUE TITLE
Trouble building qt5 on gkiss

### ISSUE THREAD

**Issue by trunc88** [kiss-community/community#499]
qt5 build is failing for me on GKISS. Posting the issue here as I don't believe it's glibc related. I apologize if it is. Here's the error:

> `In file included from ssl/qsslcertificate.cpp:135:
ssl/qsslsocket_openssl_symbols_p.h:367:29: error: 'BIO_ADDR' has not been declared
  367 | int q_DTLSv1_listen(SSL *s, BIO_ADDR *client);
      |                             ^~~~~~~~
ssl/qsslsocket_openssl_symbols_p.h:368:1: error: 'BIO_ADDR' does not name a type
  368 | BIO_ADDR *q_BIO_ADDR_new();
      | ^~~~~~~~
ssl/qsslsocket_openssl_symbols_p.h:369:6: error: variable or field 'q_BIO_ADDR_free' declared void
  369 | void q_BIO_ADDR_free(BIO_ADDR *ap);
      |      ^~~~~~~~~~~~~~~
ssl/qsslsocket_openssl_symbols_p.h:369:22: error: 'BIO_ADDR' was not declared in this scope
  369 | void q_BIO_ADDR_free(BIO_ADDR *ap);
      |                      ^~~~~~~~
ssl/qsslsocket_openssl_symbols_p.h:369:32: error: 'ap' was not declared in this scope
  369 | void q_BIO_ADDR_free(BIO_ADDR *ap);
      |                                ^~
compiling text/qdistancefield.cpp
make[2]: *** [Makefile:25499: .obj/qsslcertificate.o] Error 1
make[2]: Leaving directory '/tmp/23564/build/qt5/src/network'
make[1]: *** [Makefile:245: sub-network-make_first] Error 2
make[1]: *** Waiting for unfinished jobs....
`

[And here is the full log](https://clbin.com/IT9Cb)

Thank you

**Comment by dilyn-corner** [comment]
This is a problem specifically with `libressl` and dtls. I was in the process of trying to see what all breaks disabling it, but I've been roadblocked by a `qt5-webengine` problem :) 

In the meantime, you can add `-no-dtls` to the `qt5` build script. YMMV.

**Comment by trunc88** [comment]
Thanks, that did allow me to successfully compile qt5. Good luck with webengine

**Comment by sdsddsd1** [comment]
https://github.com/kiss-community/community/commit/43b4e34209b31c1144ddfe26100e9d7a0458e3d8 needs testing.

**Comment by dilyn-corner** [comment]
@sdsddsd1 confirmed that `falkon` isn't horrifically broken, and that is confirmation enough for me.

We'll have to watch this though (:
