### ISSUE TITLE
uthash: drop install -t

### ISSUE THREAD

**Issue by dilyn-corner** [kiss-community/community#516]
@git-bruh 

Your friendly neighborhood Midfavila has humbly(?) requested that `uthash` not use install -t because *base.
Also it's not actually required in this case.

**Comment by git-bruh** [comment]
amfora
bkeymaps
chromium
gnu-efi
neomutt
os-prober
protobuf
rbw-bin
refind
restic
runit
uthash
vundle have -t usage too
