### ISSUE TITLE
Packages with Xorg dependency

### ISSUE THREAD

**Issue by sdsddsd1** [kiss-community/community#550]
This should be most of the packages with Xorg dependencies. Feel free to add more suiteable findings and
complete the github usernames :p
I think _most_ of them have to go because they are specific to X.

- [x] 2bwm @Vouivre
- [x] azpainter @Vouivre
- [ ] bdftopcf @aaronNGi 
- [x] berry @lowercasename
- [x] bitfetch dylanaraps -> drop
- [ ] brownout 
- [x] bspwm @konimex
- [x] conky @dilyn-corner 
- [x] cwm @xuxiaodong 
- [x] dmenu @konimex
- [x] dwm @fanboimsft
- [ ] dzen @TAAPArthur
- [x] emacs @Vouivre
- [x] feh @dilyn-corner 
- [ ] fltk @mcpcpc
- [x] freeglut dylanaraps -> drop
- [x] herbe @Vouivre
- [ ] hsetroot sirtomato(long not seen)
- [x] i3-gaps @Ominitay 
- [x] i3 @Ominitay 
- [ ] imlib2 @noocsharp ?h
- [x] lemonbar @konimex
- [x] lesstif @sdsddsd1
- [x] libxaw3d @Vouivre
- [ ] maim camille
- [ ] numlockx aicx ( long not seen)
- [x] picom @konimex
- [x] pinentry-dmenu @Vouivre
- [x] rxvt-unicode @konimex
- [ ] sct @mmatongo
- [ ] setroot camille
- [ ] slock palone ( long time not seen)
- [x] surf @git-bruh 
- [ ] sx perrish
- [x] sxiv @Vouivre
- [x] tabbed @Vouivre
- [ ] x11vnc @mcpcpc
- [x] xbanish @GullikX
- [ ] xbg @mcpcpc
- [ ] xcb-util-xrm
- [ ] xclip niko tidar
- [x] xcompmgr @konimex
- [ ] xdotool
- [x] xf86-input-mtrack @dilyn-corner 
- [ ] xf86-input-synaptics rio6
- [x] xf86-input-wacom @GullikX
- [x] xf86-video-fbdev @xuxiaodong
- [ ] xhost
- [ ] xkb-switch
- [ ] xmodmap @kiedtl
- [ ] xsel @aaronNGi
- [ ] xssstate friendly neighbourhood
- [x] xtrlock @git-bruh 
- [x] xwallpaper @git-bruh 
- [ ] xwm @mcpcpc
- [ ] glu @ioraff
- [ ] glew zola
- [ ] scrot

**Comment by Ominitay** [comment]
Dropping mine #551

**Comment by Xeno-Hypster** [comment]
Gnuplot currently has an x dependency. That can be switched off, but another a dependency on another backend for interactive plots will need to be made if I don't drop the package. Will sit on that for a tiny bit.

**Comment by dilyn-corner** [comment]
No "super rush" on dropping these, people will just become a little confused when they no longer build :v

**Comment by sdsddsd1** [comment]
To safe some work it would prob be ok to drop multiple packages in a single commit, yeah?

**Comment by dilyn-corner** [comment]
Are you saying my workflow is bad >=|

**Comment by Xeno-Hypster** [comment]
> Gnuplot currently has an x dependency. That can be switched off, but another a dependency on another backend for interactive plots will need to be made if I don't drop the package. Will sit on that for a tiny bit.

Gonna drop this for the time being. PR incoming.

**Comment by konimex** [comment]
I'll drop all X-related packages with me as maintainer (bspwm, dmenu, lemonbar, picom, rxvt-unicode, xcompmgr).

**Comment by illiliti** [comment]
@sdsddsd1 you missed some packages

* [ ] alacritty @git-bruh -- append `--features wayland --no-default-features` to `cargo build`
* [ ] chromium @git-bruh -- use ozone-wayland
* [ ] dosbox @jedavies-dev -- does it support wayland?
* [ ] giblib @aicsx -- dependency of scrot
* [ ] grabc @xuxiaodong -- drop due to hard dependency on X
* [ ] mplayer @ilmich -- drop because we have mpv

**Comment by sdsddsd1** [comment]
There is a fork of dosbox which introduces sdl2 https://dosbox-staging.github.io/v0-75-0/#sdl2
I build the sourceforge version with sdl12-compat but refuses to start with ` failed to create an EGL window surface`.
Prob. needs libglvnd too.

**Comment by git-bruh** [comment]
Alacritty is up for grabs, since i don't use it. chromium will be updated on v92 release (1 week).

**Comment by dilyn-corner** [comment]
This is a friendly reminder that there is TWO WEEKS to sort all of this out. No need to drag these transitions out any longer than we have to. I'll be ramping up the reminders as we get closer to the end of the month.

**Comment by Vouivre** [comment]
Sorry for the time needed, I was busy and I wanted to take some time to think to this change to wayland for me. I will drop
the necessary packages in the next few days.

**Comment by sdsddsd1** [comment]
@Vouivre , if you are going to do the wayland change, there is a direct herbe port. https://github.com/muevoid/Wayherb

**Comment by Vouivre** [comment]
@sdsddsd1 thank you, I didn't know about the wayland port for herbe! :+1: I wanted to test mako, I will also test wayherbe.

**Comment by kiedtl** [comment]
I will be dropping `xmodmap`. Will submit a PR soon.

**Comment by dilyn-corner** [comment]
Your friendly neighborhood reminder that we have one week left to find replacements for any of these before they get dropped forcibly :)

**Comment by dilyn-corner** [comment]
:'( 
600493144e5babf201a64a0c4714e0c3c1ad3e34
