### ISSUE TITLE
Moving xorg to this repository

### ISSUE THREAD

**Issue by BrentBoyMeBob** [kiss-community/community#573]
Even though KISS is moving towards Wayland, some may be hesitant towards the shift. I'm noticing that packages are already starting to get dropped, and I do think people should have the option to use xorg related programs, even though it will result in more packages. Some people just cannot let go of xorg and some need a certain program that uses it, of which I'm proposing to call the community repository it's new home. It seems pretty reasonable to me, as the community repository has always been where most of the alternate options come from. What do you guys think?

**Comment by Xeno-Hypster** [comment]
With the shift to Wayland in the main repo, the community repo is moving to support that shift. @dilyn-corner has already indicated as such in his [most recent news post](https://k1sslinux.org/news/20210712a). There is a possibility that the kiss-community/repo will become a community fork for xorg support but you can always fork off an xorg repo or use an [xorg fork](https://github.com/ehawkvu/kiss-xorg).

**Comment by ehawkvu** [comment]
I'd also like to mention that I've been working on saving some of the recently dropped community packages. They're available in my xorg repo under 'community/' if you want to use them.

**Comment by BrentBoyMeBob** [comment]
Now that I think about it, that does make more sense, having an optional repository is actually a better approach, as it allows for choice of Wayland or xorg, while also being up to date. It allows both repositories to be more focused, which I definitely respect, since KISS has always been about variety, and there isn't supposed to be one monolithic repository, rather dozens of organized ones.
