### ISSUE TITLE
libcap new release (2.51)

### ISSUE THREAD

**Issue by e1QXR3o4AlfnrLJsZHj65TGzChF8Mg9E07yIvSV** [kiss-community/community#585]
See: https://kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.51.tar.xz

@mmatongo

**Comment by mmatongo** [comment]
I just got a new laptop, I'll be updating anything I maintain within the next 2-4 hours

**Comment by mmatongo** [comment]
Created a pull request.

**Comment by e1QXR3o4AlfnrLJsZHj65TGzChF8Mg9E07yIvSV** [comment]
#590
