### ISSUE TITLE
Checksum cleanups

### ISSUE THREAD

**Issue by jedahan** [kiss-community/community#599]
There are a number of packages where `sources` and `checksum` have a different number of lines.

I am not sure if they are always supposed to match, so this might be a case where my linter is being too aggressive.

That said, some of the formats are a bit out of date (like aerc-git), so I wanna make a tracking issue and hopefully get the maintainers of said packages to have a look at them. I will also take a look but I am not super knowledgeable about each package.

### missing checksums
- [x] mc

### needs review
- [x] aerc-git
- [x] android-tools
- [x] chromium
- [x] maim
- [x] sbase
- [x] sysmgr
- [x] ubase
- [ ] zathura-pdf-mupdf

```
 ▲ ../../kiss-repo/kiss-lint/files/kiss-lint .
./aerc-git/checksums: does not match number of sources
./android-tools/checksums: does not match number of sources
./chromium/checksums: does not match number of sources
./maim/checksums: does not match number of sources
./mc/checksums: does not match number of sources
./sbase/checksums: does not match number of sources
./sysmgr/checksums: does not match number of sources
./ubase/checksums: does not match number of sources
./zathura-pdf-mupdf/checksums: does not match number of sources
```

**Comment by jedahan** [comment]
I think most of these are false errors, i need to be smarted about skipping checksums for `git+git://` entries.

**Comment by dilyn-corner** [comment]
Can you rerun this and lmk? We can probably get all this stuff merged tonight.

**Comment by jedahan** [comment]
```
warning ./9base/checksums does not match number of sources
error ./cmus/version file is executable
warning ./goimports/checksums does not match number of sources
warning ./hummingbird-git/checksums does not match number of sources
warning ./kiss-encryption/checksums does not match number of sources
error ./libmad/version file is executable
warning ./mc/checksums does not match number of sources
warning ./retrogram-rtlsdr/checksums does not match number of sources
warning ./scroll/checksums does not match number of sources
error ./spotifyd/build file is not executable
warning ./tcc/checksums does not match number of sources
warning ./tuitube/checksums does not match number of sources
warning ./vmwh/checksums does not match number of sources
warning ./wyeb/checksums does not match number of sources
warning ./wyebadblock/checksums does not match number of sources
warning ./zathura-pdf-mupdf/checksums does not match number of sources
```

**Comment by jedahan** [comment]
https://github.com/kiss-community/community/pull/723 fixes the 3 errors. Looking into the warnings right now

**Comment by jedahan** [comment]
https://github.com/kiss-community/community/pull/724 fixes 11/13 warnings
