### ISSUE TITLE
lld: broken package

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/community#668]
@ominitay The lld package is missing a dependency on cmake, and also doesn't build since the compact_unwind_encoding.h file is not present, the old workaround is still needed. It would work fine only on systems that previously had lld installed since lld installs the /usr/include/mach-o/compact_unwind_encoding.h file.

**Comment by ominitay** [comment]
> @ominitay The lld package is missing a dependency on cmake, and also doesn't build since the compact_unwind_encoding.h file is not present, the old workaround is still needed. It would work fine only on systems that previously had lld installed since lld installs the /usr/include/mach-o/compact_unwind_encoding.h file.

Ah. It had built fine without on my system, but that explains it. Will fix that when I get to my PC later today.
