### ISSUE TITLE
Dropping my packages

### ISSUE THREAD

**Issue by GullikX** [kiss-community/community#710]
Hi guys!

Using kiss has been really fun and awesome, but now I need to focus on some other things in life. My packages are first come, first serve! :)

- [X] ~~lm-sensors~~ @dilyn-corner 
- [ ] ~~wireguard-tools~~ dropped

**Comment by noocsharp** [comment]
I can take `wireguard-tools`

**Comment by GullikX** [comment]
> I can take `wireguard-tools`

Open a pull request and I will cross it off the list.
