### ISSUE TITLE
gdb 11.1 build fail

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/community#713]
LOG
https://0x0.st/-Y8s.txt

Looking at the log, it seems that gdb now requires GMP library by configure script.

"configure: error: GMP is missing or unusable"

I would also like to point out that GMP is considered harmful.
IE. see https://suckless.org/sucks/

**Comment by kyx0r** [comment]
@Xeno-Hypster

**Comment by kyx0r** [comment]
I'll take a look maybe it can be disabled by some option.

**Comment by kyx0r** [comment]
Neither --with-gmp=no or --without-gmp works
It compiles fine if I install GMP on my system. What a curse.
Looking though the code, it includes GMP.h from gdb/gdbtypes.h
which in turn gets included all over the codebase.

Not suprised them using gmp, this project is doomed anyway...

Just add the gmp to the depends file I guess, or just freeze the version
at 10.* which did not use gmp, (or they vendored it, idk)

**Comment by Xeno-Hypster** [comment]
Hey sorry about the delay in response. Yeah, the new dependency on GMP is frustrating. I swear I went and added it to the dep file, but guess not. Added a PR with the fixed depends file.
