### ISSUE TITLE
Appimages don't work!

### ISSUE THREAD

**Issue by luizbra** [kiss-community/community#714]
I have the FUSE filesystem built-in to the kernel and the fuse2 package installed, but whenever I try to run an appimage this happens:

    -sh: ./LibreWolf-92.0-1.x86_64.AppImage: not found

**Comment by dilyn-corner** [comment]
Aren't appimages actually just lying about their 'it runs anywhere' claim because they're just built against glibc

Sep 24, 2021, 11:52 AM by ***@***.***:

**Comment by dilyn-corner** [comment]
Specifically I am talking about the discussion in https://github.com/AppImage/AppImageKit/issues/1112

**Comment by kyx0r** [comment]
Also this :) https://github.com/AppImage/AppImageKit/issues/1113

Been there, experienced it. Not considering Appimage format any good afterwards. 
Torvalds was too hasty to give it good feedback.
