### ISSUE TITLE
gdb: only install necessary stuff

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/community#718]
```
--- /home/testuser/kiss/community/community/gdb/build
+++ build
@@ -17,4 +17,6 @@
     --disable-nls
 
 make
-make DESTDIR="$1" install
+
+make -C gdb DESTDIR="$1" install
+make -C gdbserver DESTDIR="$1" install
```

@Xeno-Hypster

gdb installs a bunch of un-needed stuff that creates alternatives to binutils-provided files, this fixes it

**Comment by Xeno-Hypster** [comment]
Oh heck I missed the ping for this, sorry.

Cheers, I'll patch the build, always appreciated.
