### ISSUE TITLE
iosevka-nerd-fonts

### ISSUE THREAD

**Issue by arnolddinkla** [kiss-community/community#813]
iosevka-nerd-fonts build failure

-> iosevka-nerd-fonts Building package (1/1)
-> iosevka-nerd-fonts Extracting sources
-> iosevka-nerd-fonts Starting build
install: can't stat '*.ttf': No such file or directory
-> iosevka-nerd-fonts Build failed

**Comment by dilyn-corner** [comment]
Ah. `kiss` stopped supporting `.zip` sources a while back.

Fixed by 38ca059bde1d0d87641853830848dff33eccf818
