### ISSUE TITLE
[Tracker] Adoptable Packages

### ISSUE THREAD

**Issue by dilyn-corner** [kiss-community/community#864]
If anybody feels like maintaining more things, you are more than welcome to adopt the following packages.

Mention this issue when adopting.

Comment on this issue to orphan.

- [ ] `aria2`
- [ ] `birch`
- [ ] `bkeymaps`
- [ ] `caddy`
- [ ] `ccls`
- [ ] `crosstool-ng`
- [ ] `falkon`
- [ ] `fff`
- [ ] `hack`
- [ ] `hexyl`
- [ ] `iosevka-nerd-fonts`
- [ ] `keyutils`
- [ ] `libtirpc`
- [ ] `lm-sensors`
- [ ] `lz4`
- [ ] `neofetch`
- [ ] `pciutils`
- [ ] `qt5-declarative`
- [ ] `qt5-svg`
- [ ] `qt5-wayland`
- [ ] `qt5-webchannel`
- [ ] `qt5-webengine`
- [ ] `qt5`
- [ ] `rage`
- [ ] `ranger`
- [ ] `runit`
- [ ] `sbase`
- [ ] `shfm`
- [ ] `shinit`
- [ ] `sysmgr`
- [ ] `ubase`
- [ ] `wyeb`
- [ ] `wyebadblock`
- [ ] `zzz`

#### For Reference
The following packages are assumed orphaned:
- [ ] `chorizo`
- [ ] `ed`
- [ ] `exa`
- [ ] `glib-networking`
- [ ] `harfbuzz-icu`
- [ ] `libsoup`
- [ ] `webkit2gtk`
- [ ] `sc`
- [ ] `eudev`
- [ ] `libtool`
- [ ] `libunistring`
- [ ] `libuv`
- [ ] `libxslt`
- [ ] `nethogs`
- [ ] `procps-ng`
- [ ]  `ruby`
- [ ] `webkit2gtk`
- [ ] `icu`

**Comment by dilyn-corner** [comment]
@ioraff my hero

**Comment by mar-foo** [comment]
I haven't used KISS in a while so I'm dropping my packages

* glib-networking
* harfbuzz-icu
* libsoup
* webkit2gtk

**Comment by aabacchus** [comment]
see https://github.com/kiss-community/community/pull/1021: `libusb` needs a new maintainer.

**Comment by mmatongo** [comment]
I'll take ruby

**Comment by dilyn-corner** [comment]
Closing -- More convenient to annotate on the outdated tracker.
