### ISSUE TITLE
tcc: add `cc` symlink

### ISSUE THREAD

**Issue by TAAPArthur** [kiss-community/community#874]
@kyx0r Requesting that `ln -s tcc "$1/usr/bin/cc"` gets appended to the tcc build script

**Comment by AndreiSva** [comment]
this is just a bad idea.

**Comment by kyx0r** [comment]
I agree that this is a bad idea because - I can understand gcc package doing so because it is sort of a "default" compiler on kiss so it can assume to be that role. But doing this on a minor compiler can lead to unindeded side effects. I would leave this up to the user's discretion.

**Comment by dilyn-corner** [comment]
It's worth noting that creating the symlink just means that users can either use `kiss a tcc /usr/bin/cc` OR set `CC=tcc` in the environment, but creating the symlink wouldn't change default `cc`.

Also worth mentioning that `mold` doesn't support LTO and only recently saw its 1.0.0 release, and Dylan had still opted to create the `ld` symlink for `mold`. Just to create some context around this sort of decision; it isn't inherently dangerous, as it still requires user intervention.

I don't know how much this really matters; anyone using `tcc` should very well know its limitations and understand the hurdles.

**Comment by TAAPArthur** [comment]
In my setup tcc is my default compiler and ran into trouble when certain programs ignored my CC env var and just tried to use `/usr/bin/cc`. 

I don't see the harm. I wouldn't affect anyone who didn't explicitly enable it (unless gcc wasn't installed). Think it is better to have symmetry among compilers instead of playing favorites

**Comment by dilyn-corner** [comment]
I think this issue can be closed. Feel free to add the symlink if you would like.
