### ISSUE TITLE
Dropping packages

### ISSUE THREAD

**Issue by Xeno-Hypster** [kiss-community/community#921]
I've switched distros (needed some glibc stuff and cbf jumping to gkiss). I won't be able to maintain these packages, esp with deadlines coming up. Outside of gdb, the rest are all pretty slow updating and easy to maintain.

~~amfora~~, ed, ~~gdb~~, ~~gsl~~, sc

**Comment by aabacchus** [comment]
amfora: d07fd1144700ccc8898184091f48ce85db2e8167
